# Generated by Django 3.2.6 on 2021-08-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20210825_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='--------------', max_length=254),
        ),
    ]
