# Generated by Django 3.2.6 on 2021-08-31 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210831_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='author',
        ),
        migrations.DeleteModel(
            name='CityPermissions',
        ),
    ]
